name: Check
on:
  pull_request:
    branches:
      - master

jobs:
  check1:
    name: My check 1
    runs-on: ubuntu-latest
    steps:
    - name: Sleep for 30 seconds
      uses: jakejarvis/wait-action@master
      with:
        time: '30s'
    - name: End job
      run: exit 0;

  check2:
    name: My check 2
    runs-on: ubuntu-latest
    steps:
    - name: Sleep for 10 seconds
      uses: jakejarvis/wait-action@master
      with:
        time: '10s'
    - name: End job
      run: exit 1;
    - name: Restart if failed
      if: github.event_name == 'push' && failure()
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.PAT }}
        event-type: restart
        client-payload: '{"run_id": "${{ github.run_id }}"}'